server:
  port: 5000
  servlet:
    context-path: /

logging:
  level:
    root: info
    org:
      flywaydb: debug

spring:
  profiles:
    active: local
  application:
    name: similar-product

services-api:
  cmd:
    product:
      base-url: http://localhost:3001
      connect-timeout: 100
      read-timeout: 100
      write-timeout: 100
      max-request: 100
      logEnabled: true